---
# AWX Project Configuration

# Project Details
name: mssql-deploy
description: MSSQL Server Installation and Configuration via Ansible
organization: Default
scm_type: git
scm_url: "git@gitlab.com:mozahidhossaingitlab-group/my-devops-project.git"
scm_branch: main
scm_clean: true
scm_delete_on_update: false
scm_update_on_launch: true
scm_update_cache_timeout: 0
credential: gitlab-ssh-credential
local_path: _awx_my_devops_project
