---
# Default variables for the mssql_build role
mssql_version: "2019"
mssql_edition: "Developer"
mssql_service_user: "mssql"
sa_password: "YourStr0ng!Passw0rd"
backup_dir: "/var/opt/mssql/backups"
data_dir: "/var/opt/mssql/data"
log_dir: "/var/opt/mssql/log"
mssql_port: 1433
mssql_tools_path: "/opt/mssql-tools/bin"
mssql_memory_limit_mb: 512
